import test from 'node:test';import assert from 'node:assert/strict';import {extraStructures,patternCatalogue} from '../patterns.mjs';import {structures,evaluateStrategy} from '../strategy.mjs';
const bar=(i,close,values={})=>({time:1700000000+i*86400,open:close,close,high:close+0.2,low:close-0.2,volume:1000000,...values});
const mirror=b=>b.map(p=>({...p,open:300-p.open,close:300-p.close,high:300-p.low,low:300-p.high}));
const find=(bars,name,atr=3)=>{const p=structures(bars,atr).find(p=>p.type===name);assert.ok(p,name);return p;};
function triple(head=false){const b=Array.from({length:45},(_,i)=>bar(i,104,{high:108,low:101}));for(const [i,value]of [[10,95],[22,head?90:95.2],[34,95.1]])b[i].low=value;b[44]=bar(44,110);return b;}
function geometry(upper,lower,exit){const b=Array.from({length:60},(_,i)=>{const u=upper(i),l=lower(i),c=(u+l)/2+Math.cos(i*Math.PI/3)*(u-l)/2;return bar(i,c);});b[59]=bar(59,exit);return b;}
function pole(pennant=false){return Array.from({length:60},(_,i)=>{if(i<39)return bar(i,100);if(i<47)return bar(i,100+(i-39)*4);const j=i-47,u=133-(pennant?0.3:0.1)*j,l=125+(pennant?0.2:-0.1)*j;return bar(i,i===59?134:(u+l)/2+Math.cos(j*Math.PI/2)*(u-l)/2);});}
test('catalogue is unique, broad and only lists implemented output names',()=>{assert.equal(new Set(patternCatalogue).size,34);assert.ok(patternCatalogue.includes('Bear Pennant'));assert.ok(patternCatalogue.includes('Morning Star'));});
test('triple reversals and shoulders use confirmed points',()=>{assert.equal(find(triple(),'Triple Bottom').state,'breakout');assert.equal(find(mirror(triple()),'Triple Top').state,'breakdown');const p=find(triple(true),'Inverse Head and Shoulders');assert.equal(p.direction,'bullish');assert.ok(p.points.every(p=>p.knownAt<=triple(true).at(-1).time));assert.equal(find(mirror(triple(true)),'Head and Shoulders').direction,'bearish');});
test('rectangles, triangles and channels require actual repeated boundary contacts',()=>{assert.equal(find(geometry(()=>120,()=>100,124),'Rectangle').state,'breakout');find(geometry(()=>120,i=>100+0.2*i,124),'Ascending Triangle');find(geometry(i=>120-0.2*i,()=>100,96),'Descending Triangle');find(geometry(i=>120-0.1*i,i=>100+0.1*i,124),'Symmetrical Triangle');find(geometry(i=>120+0.2*i,i=>100+0.2*i,138),'Ascending Channel');find(geometry(i=>120-0.2*i,i=>100-0.2*i,100),'Descending Channel');});
test('wedges retain direction and confirmed boundary break',()=>{assert.equal(find(geometry(i=>150-0.4*i,i=>125-0.2*i,132),'Falling Wedge').state,'breakout');assert.equal(find(geometry(i=>120+0.2*i,i=>95+0.4*i,110),'Rising Wedge').state,'breakdown');});
test('flags and pennants require pole and shallow pause, mirror supports warnings',()=>{find(pole(),'Bull Flag');find(mirror(pole()),'Bear Flag');find(pole(true),'Bull Pennant');find(mirror(pole(true)),'Bear Pennant');});
test('engulfing and star candle models retain bullish and bearish sides',()=>{const b=[bar(0,110),bar(1,108),bar(2,107),bar(3,102,{open:106,high:107,low:101}),bar(4,107,{open:101,high:108,low:100})];assert.equal(find(b,'Bullish Engulfing').category,'candle');assert.equal(find(mirror(b),'Bearish Engulfing').direction,'bearish');const star=[bar(0,110),bar(1,109),bar(2,100,{open:108,high:109,low:99}),bar(3,99.5,{open:100,high:101,low:99}),bar(4,106,{open:100,high:107,low:99.5})];find(star,'Morning Star');find(mirror(star),'Evening Star');});
test('a single spike cannot substitute for chart boundary contacts',()=>{const b=Array.from({length:60},(_,i)=>bar(i,100+i*0.2));b[59]=bar(59,140);assert.equal(extraStructures(b,3).some(p=>['Rectangle','Ascending Triangle','Bull Flag'].includes(p.type)),false);});
test('reward must be at least twice risk even if lower threshold requested',()=>{const b=Array.from({length:170},(_,i)=>bar(i,127,{open:125,low:124,high:130}));b[140].high=155;b[150].low=120;b[162].low=120.5;b[169]=bar(169,133,{high:134,low:124,open:125});const r=evaluateStrategy(b,{minRR:1});assert.equal(r.status,'waiting');assert.equal(r.plan.minimumRR,2);assert.equal(r.plan.minimumTarget,r.plan.entry+2*(r.plan.entry-r.plan.stop));});
test('new patterns never use future bars and bearish patterns cannot create short candidates',()=>{const b=geometry(()=>120,()=>100,124);const p=extraStructures(b,3);const future=[...b,bar(60,500)];assert.deepEqual(extraStructures(future.slice(0,60),3),p);const all=Array.from({length:150},(_,i)=>bar(i,100)).concat(mirror(b).map((p,i)=>({...p,time:1700000000+(150+i)*86400})));const r=evaluateStrategy(all);assert.equal(r.side,'long');if(r.status==='candidate')assert.ok(r.plan.target-r.plan.entry>=2*(r.plan.entry-r.plan.stop));});

test('rounded reversals and mirrored legacy cup are detected',()=>{const b=Array.from({length:35},(_,i)=>bar(i,i<4?118:100+18*((i-4-14.5)/14.5)**2));b[34]=bar(34,121);find(b,'Rounding Bottom');find(mirror(b),'Rounding Top');const cup=Array.from({length:45},(_,i)=>{let close=118;if(i>5&&i<35)close=100+18*((i-20)/15)**2;if(i>35)close=116;return bar(i,close,{high:close+1,low:close-1});});cup[5].high=121;cup[35].high=121;cup[44]=bar(44,123,{high:124});find(mirror(cup),'Inverted Cup and Handle');find(mirror(triple()),'Double Top');});
test('hammer and shooting star require trend and asymmetric wick',()=>{const b=[bar(0,110),bar(1,108),bar(2,106),bar(3,104),bar(4,103,{open:102,high:103.2,low:99.9})];find(b,'Hammer');find(mirror(b),'Shooting Star');const negative=b.map(p=>({...p}));negative[4].low=101.9;assert.equal(extraStructures(negative,3).some(p=>p.type==='Hammer'),false);});
test('piercing and harami pairs support both directions',()=>{const piercing=[bar(0,112),bar(1,110),bar(2,109),bar(3,102,{open:108,high:109,low:101}),bar(4,106,{open:101,high:107,low:100})];find(piercing,'Piercing Line');find(mirror(piercing),'Dark Cloud Cover');const harami=[bar(0,112),bar(1,110),bar(2,109),bar(3,100,{open:108,high:109,low:99}),bar(4,104,{open:102,high:105,low:101})];find(harami,'Bullish Harami');find(mirror(harami),'Bearish Harami');});
test('inside bar requires mother candle breakout, not just inside range break',()=>{const b=[bar(0,100),bar(1,100),bar(2,100,{high:105,low:95}),bar(3,100,{high:103,low:97}),bar(4,106)];find(b,'Inside Bar Breakout');find(mirror(b),'Inside Bar Breakdown');b[4]=bar(4,104);assert.equal(extraStructures(b,3).some(p=>p.type==='Inside Bar Breakout'),false);});
