
import test from 'node:test';import assert from 'node:assert/strict';import {normalizeHours,fetchHours} from './hour-archive.mjs';import {fetchYahooDaily} from './yahoo.mjs';import fs from 'node:fs';
const start=Date.parse('2026-10-02T13:30:00Z')/1000;
const bars=()=>Array.from({length:7},(_,i)=>({time:start+i*3600,open:10+i,high:12+i,low:9+i,close:11+i,volume:100+i}));
const payload=()=>({chart:{result:[{meta:{symbol:'AAPL',currency:'USD',instrumentType:'EQUITY',dataGranularity:'1h'},timestamp:bars().map(b=>b.time),indicators:{quote:[Object.fromEntries(['open','high','low','close','volume'].map(k=>[k,bars().map(b=>b[k])]))]}}]}});
test('hour normalization retains regular-session alignment and excludes unfinished hour',()=>{assert.equal(normalizeHours(payload(),'AAPL',(start+3600)*1000).length,1);assert.equal(normalizeHours(payload(),'AAPL',(start+23400)*1000).length,7);const p=payload();p.chart.result[0].meta.symbol='MSFT';assert.throws(()=>normalizeHours(p,'AAPL'));});
test('one-year hourly request is keyless and uses calendar-year endpoints',async()=>{const now=new Date('2026-10-02T21:00:00Z');const result=await fetchHours('AAPL',1,async url=>{assert.equal(url.searchParams.get('interval'),'1h');assert.equal(Number(url.searchParams.get('period1')),Date.parse('2025-10-02T21:00:00Z')/1000);assert.equal(url.searchParams.has('apikey'),false);return {ok:true,json:async()=>payload()};},now);assert.equal(result.length,7);});
test('three-year daily request uses calendar endpoints instead of the old two-year range',async()=>{const now=new Date('2026-10-02T21:00:00Z');await assert.rejects(fetchYahooDaily('AAPL',async url=>{assert.equal(Number(url.searchParams.get('period1')),Date.parse('2023-10-02T21:00:00Z')/1000);assert.equal(url.searchParams.has('range'),false);return {ok:false,status:503};},now,3));});
test('daily model schedule is separated from download arrivals',()=>{const cfg=JSON.parse(fs.readFileSync(new URL('./config.json',import.meta.url),'utf8'));assert.equal(cfg.analysisIntervalMs,86400000);assert.equal(cfg.reanalyzeOnData,false);assert.equal(cfg.dailyHistoryYears,3);});
