
import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
import {normalizeMinutes,fetchMinutes,nextMinuteJob,minuteRefreshDue,createIntraday} from './intraday.mjs';
const time=Date.parse('2026-10-02T14:00:00Z')/1000,now=(time+90)*1000;
const fixture=()=>({chart:{result:[{meta:{symbol:'AAPL',currency:'USD',instrumentType:'EQUITY',dataGranularity:'1m',tradingPeriods:[[{start:time,end:time+3600}]]},timestamp:[time-60,time,time+60,time+90],indicators:{quote:[{open:[10,10,10,10],high:[11,11,11,11],low:[9,9,9,9],close:[10,10,10,10],volume:[100,100,100,100]}]}}]}});
test('minute normalization excludes unfinished, irregular quote timestamps and outside sessions',()=>{const r=normalizeMinutes(fixture(),'AAPL',now);assert.deepEqual(r.bars.map(b=>b.time),[time]);});
test('minute validation rejects wrong symbol, daily interval and malformed volume',()=>{for(const edit of [x=>x.chart.result[0].meta.symbol='MSFT',x=>x.chart.result[0].meta.dataGranularity='1d',x=>x.chart.result[0].indicators.quote[0].volume[1]=-1]){const x=fixture();edit(x);assert.throws(()=>normalizeMinutes(x,'AAPL',now));}});
test('one-minute request is keyless and access denial is not retried',async()=>{let calls=0;await assert.rejects(fetchMinutes('AAPL','5d',async url=>{calls++;assert.equal(url.searchParams.get('interval'),'1m');assert.equal(url.searchParams.has('apikey'),false);return {ok:false,status:429};}));assert.equal(calls,1);});
test('minute queue respects the same persisted Yahoo rate, pause and daily budget',()=>{assert.equal(nextMinuteJob(['AAPL'],{}, {pauseUntil:now+1},now).reason,'provider-limit');assert.equal(nextMinuteJob(['AAPL'],{}, {day:'2026-10-02',used:750},now).reason,'daily-budget');assert.equal(nextMinuteJob(['AAPL'],{}, {nextAt:now+9000},now).reason,'rate-limit');});
test('minute queue backfills missing stocks and prioritizes selected without refreshing every minute',()=>{const meta={AAPL:{fetchedAt:now-120000}};assert.equal(nextMinuteJob(['AAPL','MSFT'],meta,{},now,'AAPL').symbol,'MSFT');meta.AAPL.fetchedAt=now-600000;assert.equal(nextMinuteJob(['AAPL','MSFT'],meta,{},now,'AAPL').symbol,'AAPL');});
test('existing minute stocks do not consume repeated requests before opening or over weekends',()=>{assert.equal(minuteRefreshDue({fetchedAt:now},Date.parse('2026-10-03T14:00:00Z'),300000),false);assert.equal(minuteRefreshDue({fetchedAt:now},Date.parse('2026-10-05T12:00:00Z'),300000),false);assert.equal(minuteRefreshDue({fetchedAt:now},Date.parse('2026-10-02T21:00:00Z'),300000),true);});
test('minute archive restores progress separately from daily tables and selected details',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE daily_history(symbol TEXT,payload TEXT); INSERT INTO daily_history VALUES('AAPL','daily marker')");const opts={db,symbols:['AAPL'],getQuota:()=>({}),consume:()=>{},pause:()=>{},broadcast:()=>{}};const first=createIntraday(opts);db.prepare('INSERT INTO minute_bars VALUES(?,?,?,?,?,?,?)').run('AAPL',time,10,11,9,10,100);db.prepare('INSERT INTO minute_meta VALUES(?,?)').run('AAPL',JSON.stringify({fetchedAt:now,status:'ready'}));const restored=createIntraday(opts);assert.equal(restored.summary().loaded,1);assert.equal(restored.detail('AAPL').bars.length,1);assert.equal(db.prepare('SELECT payload FROM daily_history').get().payload,'daily marker');first.stop();restored.stop();db.close();});

test('background download persists completed minute bars and consumes one shared credit',async()=>{
 const db=new DatabaseSync(':memory:');let credits=0;
 const opts={db,symbols:['AAPL'],getQuota:()=>({}),consume:()=>credits++,pause:()=>{},broadcast:()=>{},fetcher:async()=>({ok:true,json:async()=>fixture()})};
 const archive=createIntraday(opts);await archive.tick();assert.equal(credits,1);assert.equal(archive.detail('AAPL').bars.length,2);assert.equal(archive.summary().loaded,1);
 const restored=createIntraday(opts);assert.equal(restored.detail('AAPL').bars.length,2);archive.stop();restored.stop();db.close();
});
